// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automotive_ai/world/new_traffic_service.proto

#include "automotive_ai/world/new_traffic_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace automotive_ai {
namespace world {
}  // namespace world
}  // namespace automotive_ai
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n-automotive_ai/world/new_traffic_servic"
  "e.proto\022\023automotive_ai.world\032\033google/pro"
  "tobuf/empty.proto\032.automotive_ai/common/"
  "new_traffic_vehicle.proto2\373\001\n\021NewTraffic"
  "Service\022S\n\rReportTraffic\022(.automotive_ai"
  ".common.NewTrafficVehicles\032\026.google.prot"
  "obuf.Empty\"\000\022P\n\nGetTraffic\022\026.google.prot"
  "obuf.Empty\032(.automotive_ai.common.NewTra"
  "fficVehicles\"\000\022\?\n\013StepNextEnd\022\026.google.p"
  "rotobuf.Empty\032\026.google.protobuf.Empty\"\000B"
  "\006\242\002\003AAIb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto_deps[2] = {
  &::descriptor_table_automotive_5fai_2fcommon_2fnew_5ftraffic_5fvehicle_2eproto,
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto_once;
static bool descriptor_table_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto = {
  &descriptor_table_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto_initialized, descriptor_table_protodef_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto, "automotive_ai/world/new_traffic_service.proto", 415,
  &descriptor_table_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto_once, descriptor_table_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto_sccs, descriptor_table_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto_deps, 0, 2,
  schemas, file_default_instances, TableStruct_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto::offsets,
  file_level_metadata_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto, 0, file_level_enum_descriptors_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto, file_level_service_descriptors_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_automotive_5fai_2fworld_2fnew_5ftraffic_5fservice_2eproto), true);
namespace automotive_ai {
namespace world {

// @@protoc_insertion_point(namespace_scope)
}  // namespace world
}  // namespace automotive_ai
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
